name: open_file_safe_plus
description: A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
version: 0.0.3
homepage: https://github.com/mdshadatrahman/open_file_plus

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.crazecoder.openfile
        pluginClass: OpenFilePlugin
      ios:
        pluginClass: OpenFilePlugin
